Flask_Blog/Flask_app/posts/forms.py
from flask_wtf import FlaskForm 
from wtforms import StringField , TextAreaField , SubmitField
from wtforms.validators import DataRequired 


class PostForm(FlaskForm):
   title = StringField("Title",validators=[DataRequired()])
   content  = TextAreaField('Content',validators=[DataRequired()])
   submit = SubmitField('Post')
   

Flask_Blog/Flask_app/main/routes.py
from flask import Blueprint , render_template , request
from Flask_app.models import Post


main = Blueprint('main',__name__)



@main.route('/')
@main.route('/home')
def home():

    page = request.args.get('page',1,type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(per_page=5,page=page)
    return render_template('home.html',posts=posts)

@main.route('/about')
def about():
    return render_template('about.html')

Flask_Blog/Flask_app/posts/routes.py
from flask import Blueprint , render_template, url_for , flash , redirect,abort , request
from flask_login import current_user , login_required
from Flask_app.posts.forms import PostForm
from Flask_app.models import Post , User
from Flask_app import db
posts = Blueprint('posts',__name__)



@posts.route("/post/new",methods =['GET','POST'])
@login_required
def new_post():

    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data , content=form.content.data , author = current_user)
        db.session.add(post)
        db.session.commit()
        flash("Your post has been created",'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html',title='New Post', form =form, legend='New Post')

@posts.route("/user/<string:username>")
def user_post(username):
    page  = request.args.get('page',1,type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page,per_page=5)
    return render_template('user_posts.html',posts=posts,user=user)

@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html',title=post.title,post=post)

@posts.route("/post/<int:post_id>/update", methods=["GET","POST"])
@login_required
def update_post(post_id):

    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data 
        post.content = form.content.data 
        db.session.commit()
        flash("Post been updated",'success')
        return redirect(url_for('posts.post',post_id=post_id))
    elif request.method == "GET":
      form.title.data = post.title
      form.content.data = post.content
    return render_template('create_post.html',title="Update Post",form = form, legend='Update Post')

@posts.route('/post/<int:post_id>/delete',methods=['POST'])
@login_required
def delete_post(post_id):

    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash("Your post has been deleted",'success')
    return redirect(url_for('main.home'))

Flask_Blog/Flask_app/users/routes.py
from flask import Blueprint , render_template , url_for , flash , redirect , request
from flask_login import current_user ,logout_user , login_user , login_required
from Flask_app.users.utils import save_picture , send_reset_email
from Flask_app.users.forms import LoginForm,RegistrationForm , RequestResetForm , UpdateAccountForm ,ResetPasswordForm
from Flask_app.models import User,Post


users = Blueprint('users',__name__) 

@users.route("/register",methods=['GET','POST'])
def register():
    from Flask_app import db,bcrypt

    if current_user.is_authenticated:
         return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hash_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data,email = form.email.data , password = hash_password)
        db.session.add(user)
        db.session.commit()
        flash("Account was created",'success')
        return redirect(url_for('users.login'))
    return render_template('register.html',title="Register",form=form)

@users.route("/login",methods=["GET","POST"])
def login():
    from Flask_app import bcrypt

    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password,form.password.data):
            login_user(user,remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash("Login Unsuccesful Please check email and password","danger")    
    return render_template("login.html",title="Login",form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route('/account',methods=['GET','POST'])
@login_required
def account():
    from Flask_app import db,bcrypt
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data 
        current_user.email = form.email.data 
        db.session.commit()
        flash('account been updated','success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static',filename='profile_pics/'+current_user.image_file)
    return render_template('account.html',title='Account',
                           image_file=image_file, form=form)




@users.route("/reset_password",methods=["GET","POST"])
def reset_request():
   if current_user.is_authenticated:
       return redirect(url_for('main.home'))
   form = RequestResetForm()
   if form.validate_on_submit():
       user = User.query.filter_by(email=form.email.data).first()
       send_reset_email(user)
       flash('an email has been sent with instruction to reset password','info')
       return redirect(url_for('users.login'))
   return render_template('reset_request.html',title='Reset Password',form = form)

@users.route('/reset_password/<token>',methods=["GET","POST"])
def reset_token(token):
    from Flask_app import db,bcrypt
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
         flash('That is an invalid or expired token','warning')
         return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your account has been updated! You are now able to log in ','success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html',title='Reset Password',form=form)

Flask_Blog/Flask_app/templates/about.html
{% extends "layout.html" %}
{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-8 mx-auto text-center ">
            <h1 class="display-4 text-dark">About Flask Blog</h1>
            <p class="lead text-muted text-dark">A simple, elegant, and efficient way to share your thoughts with the world.</p>
            <hr class="my-4">
            <p class="text-justify text-dark">
                Flask Blog is a lightweight, yet powerful blogging platform built with Flask, Python, and SQLAlchemy.
                Whether you're a tech enthusiast, writer, or developer, this blog serves as a space to create, share,
                and engage with content effortlessly.
            </p>
            <div class="mt-4">
                <a href="{{ url_for('main.home') }}" class="btn btn-primary">Go to Home</a>
              {%if current_user.is_authenticated == False%}
                <a href="{{ url_for('users.register') }}" class="btn btn-success">Get Started</a>
              {%endif%}
            </div>
        </div>
    </div>
</div>
{% endblock content %}

Flask_Blog/Flask_app/templates/home.html
{% extends "layout.html" %}
{% block content%}
    {% for post in posts.items %}
       <article class="media content-section p-3 border">
        <img class="rounded-circle account-img"  src="{{url_for('static',filename='profile_pics/'+post.author.image_file)}}">
         <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2 text-primary" href="{{url_for('posts.user_post',username=post.author.username)}}">{{post.author.username}}</a>
              <small class="text-muted">{{post.date_posted.strftime('%Y-%m-%d')}}</small>
            </div>
            <h2><a class="article-title text-dark" href="{{url_for('posts.post',post_id=post.id)}}">{{post.title}}</a></h2>
            <p class="article-content">{{post.content}}</p>
         </div>
       </article>
    {% endfor %} 
   {%for page_num in posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2)%}
    {%if page_num%}
      {%if posts.page == page_num%}
       <a class="btn btn-info mb-4" href="{{url_for('main.home',page=page_num)}}">{{page_num}}</a>
       {%else%}
      <a class="btn btn-outline-info mb-4" href='{{url_for("main.home",page=page_num)}}'>{{page_num}}</a>
       {%endif%}
    {%else%}
      ...
    {%endif%}
    {%endfor%}
{% endblock content %}

Flask_Blog/Flask_app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static',filename='css/styles.css')}}">
    {% if title %}
      <title>Flask Blog - {{title}}</title>
    {% else %}
       <title>Flask Blog</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand text-white" href="/">Flask Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navabarNav" aria-expanded="false" aria-label="Toogle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
     <ul class="navbar-nav">
        <li class="nav-item text-white">
            <a class="nav-link" href="{{ url_for('main.home')}}">Home</a>
        </li>
        <li class="nav-item text-white">
            <a class="nav-link" href="{{url_for('main.about')}}">About</a>
        </li>
        {% if current_user.is_authenticated %}
        <li class="nav-item text-white">
            <a class="nav-link" href="{{url_for('posts.new_post')}}">New Post</a>
        </li>
        <li class="nav-item text-white">
            <a class="nav-link" href="{{ url_for('users.account')}}">Account</a>
        </li>
        <li class="nav-item text-white">
           <a class="nav-link" href="{{ url_for('users.logout')}}">Logout</a>
        </li>
        {%else%}
        <li class="nav-item text-white">
            <a class="nav-link" href="{{url_for('users.login')}}">Login</a>
        </li>
        <li class="nav-item text-white">
            <a class="nav-link" href="{{url_for('users.register')}}">Register
        </li>
        {% endif %}
        
     </ul>
    </div>
    </nav>
</header>
<main role="main" class="container">
   
    <div class="row">
        <div class="col-md-6 ml-0  text-dark">
           {% with messages = get_flashed_messages(with_categories=true)%}
              {%if messages%}
                {% for category, msg in messages%}
                  <div class="alert  alert-{{category}}"> {{msg}}</div>
                {%endfor%}
              {%endif%}
           {%endwith%}
           {% block content %}{% endblock content%}
        </div>
    
       <!--SideBar-->
            <div class="col-md-4 ml-auto justify-content-end oursidebar">
               <div class="card bg-dark text-white w-150">
                   <div class="card-body">
                        <h3><em>Our Sidebar</em></h3>
                        <p>You can put any information here you'd like</p>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item bg-dark text-white">Latest Posts</li>
                            <li class="list-group-item bg-dark text-white">Announcements</li>
                            <li class="list-group-item bg-dark text-white">Calendar</li>
                            <li class="list-group-item bg-dark text-white">Etc</li>
                        </ul>
                    </div>
                </div>
           </div>
    </div>
    
</main>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

Flask_Blog/Flask_app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <!-- Header (Navbar) -->
    <header class="site-header">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand text-white" href="/">Flask Blog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item text-white">
                        <a class="nav-link" href="{{url_for('main.home')}}">Home</a>
                    </li>
                    <li class="nav-item text-white">
                        <a class="nav-link" href="{{url_for('main.about')}}">About</a>
                    </li>
                    <li class="nav-item text-white">
                        <a class="nav-link" href="{{url_for('users.login')}}">Login</a>
                    </li>
                    <li class="nav-item text-white">
                        <a class="nav-link" href="{{url_for('users.register')}}">Register</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <!-- Main Content -->
    <main role="main" class="container mt-5">
        <div class="row">
            <div class="col-md-8">
                {% with messages = get_flashed_messages(with_categories=true)%}
                 {% if messages %}
                   {% for category, msg in messages%}
                     <div class="alert alert-{{category}}">
                        {{msg}}
                     </div>
                    {%endfor%}
                  {%endif%}
                {%endwith%}
                <h2>Login</h2>
                <form method="POST" action="{{ url_for('users.login') }}">
                    {{ form.hidden_tag() }}
                    
                    <!-- Email Field -->
                    <div class="form-group">
                        {{ form.email.label }}
                        {{ form.email(class="form-control form-control-lg") }}
                        {% for error in form.email.errors %}
                            <small class="text-danger">{{ error }}</small>
                        {% endfor %}
                    </div>

                    <!-- Password Field -->
                    <div class="form-group">
                        {{ form.password.label }}
                        {{ form.password(class="form-control form-control-lg") }}
                        {% for error in form.password.errors %}
                            <small class="text-danger">{{ error }}</small>
                        {% endfor %}
                    </div>
                    
                    <!--Remember Me-->
                    <div class="form-check">
                         {{form.remember(class="form-check-input")}}
                         {{form.remember.label(class="form-check-label")}}
                    </div>

                    <div class="form-group">
                        {{ form.submit(class="btn btn-outline-info btn-lg") }}
                        <small class="btn btn-outline-info">
                            <a href="{{url_for('users.reset_request')}}">Forgot Password</a>
                        </small>
                    </div>
                </form>
                
                <!-- Login Link -->
                <div>
                    <small>Don't have an account? <a href="{{ url_for('users.register') }}">Register Here</a></small>
                </div>
            </div>

            <!-- Sidebar -->
            <div class="col-md-4">
                <div class="card bg-dark text-white">
                    <div class="card-body">
                        <h3><em>Our Sidebar</em></h3>
                        <p>You can put any information here you'd like</p>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item bg-dark text-white">Latest Posts</li>
                            <li class="list-group-item bg-dark text-white">Announcements</li>
                            <li class="list-group-item bg-dark text-white">Calendar</li>
                            <li class="list-group-item bg-dark text-white">Etc</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </main>

    <!-- Scripts -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-smh86yLOldNR0p+MT1pBDo5iT2UBs3oOS5CZhDq+SSzFspQ8pBh96HJtATr5GOds" crossorigin="anonymous"></script>
</body>
</html>

Flask_Blog/Flask_app/templates/post.html
{%extends "layout.html"%}
{%block content %}
  <article class="media content-section p-3 border">
    <img class="rounded-circle account-img"  src="{{url_for('static',filename='profile_pics/'+post.author.image_file)}}">
     <div class="media-body">
        <div class="article-metadata">
          <a class="mr-2 text-primary" href="{{url_for('posts.user_post',username=post.author.username)}}">{{post.author.username}}</a>
          <small class="text-muted">{{post.date_posted.strftime('%Y-%m-%d')}}</small>
          {%if post.author == current_user%}
            <div>
               <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{url_for('posts.update_post',post_id =post.id)}}">Update</a>
               <button type="button" class="btn btn-danger bnt-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
            </div>
            {%endif%}
        </div>
        <h2><a class="article-title">{{post.title}}</a></h2>
        <p class="article-content">{{post.content}}</p>
     </div>
   </article>
   <!--Delete Modal-->
   <!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          Are you sure you want to delete this post?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{url_for('posts.delete_post',post_id=post.id)}}" method="POST">
            <input class="btn btn-danger" type="submit" value ='Delete'>
          </form>
        </div>
      </div>
    </div>
  </div>
{%endblock content%}

Flask_Blog/Flask_app/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <!-- Header (Navbar) -->
    <header class="site-header">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand text-white" href="/">Flask Blog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item text-white">
                        <a class="nav-link" href="{{url_for('main.home')}}">Home</a>
                    </li>
                    <li class="nav-item text-white">
                        <a class="nav-link" href="{{url_for('main.about')}}">About</a>
                    </li>
                    <li class="nav-item text-white">
                        <a class="nav-link" href="{{url_for('users.login')}}">Login</a>
                    </li>
                    <li class="nav-item text-white">
                        <a class="nav-link" href="{{url_for('users.register')}}">Register</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <!-- Main Content -->
    <main role="main" class="container mt-5">
        <div class="row">
            <div class="col-md-8">
                <h2>Register</h2>
                <form method="POST" action="{{ url_for('users.register') }}">
                    {{ form.hidden_tag() }}
                    <!-- Username Field -->
                    <div class="form-group">
                        {{ form.username.label }}
                        {{ form.username(class="form-control form-control-lg") }}
                        {% for error in form.username.errors %}
                            <small class="text-danger">{{ error }}</small>
                        {% endfor %}
                    </div>

                    <!-- Email Field -->
                    <div class="form-group">
                        {{ form.email.label }}
                        {{ form.email(class="form-control form-control-lg") }}
                        {% for error in form.email.errors %}
                            <small class="text-danger">{{ error }}</small>
                        {% endfor %}
                    </div>

                    <!-- Password Field -->
                    <div class="form-group">
                        {{ form.password.label }}
                        {{ form.password(class="form-control form-control-lg") }}
                        {% for error in form.password.errors %}
                            <small class="text-danger">{{ error }}</small>
                        {% endfor %}
                    </div>

                    <!-- Confirm Password Field -->
                    <div class="form-group">
                        {{ form.confirm_password.label }}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                        {% for error in form.confirm_password.errors %}
                            <small class="text-danger">{{ error }}</small>
                        {% endfor %}
                    </div>

                    <!-- Submit Button -->
                    <div class="form-group">
                        {{ form.submit(class="btn btn-outline-info btn-lg") }}
                    </div>
                </form>

                <!-- Login Link -->
                <div>
                    <small>Already have an account? <a href="{{ url_for('users.login') }}">Login</a></small>
                </div>
            </div>

            <!-- Sidebar -->
            <div class="col-md-4">
                <div class="card bg-dark text-white">
                    <div class="card-body">
                        <h3><em>Our Sidebar</em></h3>
                        <p>You can put any information here you'd like</p>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item bg-dark text-white">Latest Posts</li>
                            <li class="list-group-item bg-dark text-white">Announcements</li>
                            <li class="list-group-item bg-dark text-white">Calendar</li>
                            <li class="list-group-item bg-dark text-white">Etc</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </main>

    <!-- Scripts -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-smh86yLOldNR0p+MT1pBDo5iT2UBs3oOS5CZhDq+SSzFspQ8pBh96HJtATr5GOds" crossorigin="anonymous"></script>
</body>
</html>

Flask_Blog/Flask_app/templates/reset_request.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <!-- Header (Navbar) -->
    <header class="site-header">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand text-white" href="/">Flask Blog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item text-white">
                        <a class="nav-link" href="{{url_for('main.home')}}">Home</a>
                    </li>
                    <li class="nav-item text-white">
                        <a class="nav-link" href="{{url_for('main.about')}}">About</a>
                    </li>
                    <li class="nav-item text-white">
                        <a class="nav-link" href="{{url_for('users.login')}}">Login</a>
                    </li>
                    <li class="nav-item text-white">
                        <a class="nav-link" href="{{url_for('users.register')}}">Register</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <!-- Main Content -->
    <main role="main" class="container mt-5">
        <div class="row">
            <div class="col-md-8">
                {% with messages = get_flashed_messages(with_categories=true)%}
                 {% if messages %}
                   {% for category, msg in messages%}
                     <div class="alert alert-{{category}}">
                        {{msg}}
                     </div>
                    {%endfor%}
                  {%endif%}
                {%endwith%}
                <form method="POST" action="">
                    {{ form.hidden_tag() }}
                    
                    <!-- Email Field -->
                    <div class="form-group">
                        {{form.email.label(class='form-control-label')}}
                        {{form.email(class='form-control form-control-lg'+ ('is-invalid' if form.email.errors else ''))}}
                    </div>
                    <div class="form-group">
                        {{form.submit(class='btn btn-outline-info')}}
                    </div>
                </form>
            </div>
              

            <!-- Sidebar -->
            <div class="col-md-4">
                <div class="card bg-dark text-white">
                    <div class="card-body">
                        <h3><em>Our Sidebar</em></h3>
                        <p>You can put any information here you'd like</p>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item bg-dark text-white">Latest Posts</li>
                            <li class="list-group-item bg-dark text-white">Announcements</li>
                            <li class="list-group-item bg-dark text-white">Calendar</li>
                            <li class="list-group-item bg-dark text-white">Etc</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </main>

    <!-- Scripts -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-smh86yLOldNR0p+MT1pBDo5iT2UBs3oOS5CZhDq+SSzFspQ8pBh96HJtATr5GOds" crossorigin="anonymous"></script>
</body>
</html>